//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        public int id { get; set; }
        public string name { get; set; }
        public string releaseDate { get; set; }
        public string runTime { get; set; }
        public Nullable<double> rating { get; set; }
        public string overview { get; set; }
        public Nullable<int> genresId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual account account { get; set; }
        public virtual genres genres { get; set; }
    }
}
